#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TARGET="$(basename $0 | sed 's/-clang.*//')"
EXE=$(basename $0 | sed 's/.*-\(clang.*\)/\1/')
ARCH=$(echo $TARGET | sed 's/-.*//')
case $ARCH in
i686)
	ARCH_FLAGS=-fsjlj-exceptions
	;;
x86_64)
	ARCH_FLAGS=-fdwarf-exceptions
	;;
esac
$DIR/$EXE -target $TARGET $ARCH_FLAGS "$@"
