#!/bin/bash

PREFIX=~/llvm
eval PREFIX=$PREFIX

TARGET=armv7-w64-mingw32

export PATH=$PREFIX/usr/bin:$PATH
export MAKE=/usr/bin/make CC=$TARGET-clang CXX=$TARGET-clang++ AR=$PREFIX/usr/bin/llvm-ar-gnu RANLIB=$PREFIX/usr/bin/llvm-ranlib-gnu

cd ..
mkdir build-$TARGET-crt
cd build-$TARGET-crt

AR="llvm-ar -format gnu" \
../mingw-w64/mingw-w64-crt/configure \
    --host=$TARGET \
    --prefix=$PREFIX/usr/$TARGET \
    --enable-sdk=all \
    --enable-secure-api \
    --enable-wildcard \
    --with-sysroot=$PREFIX/usr/$TARGET \
    --with-genlib=$PREFIX/usr/bin/llvm-dlltool \
    --disable-lib32 --disable-lib64 --enable-libarm32

make -j1
make -j1 install
