#!/bin/bash

PREFIX=~/llvm
eval PREFIX=$PREFIX

TARGET=x86_64-w64-mingw32

#export PATH=$PREFIX/usr/bin:$PATH
export CC=$PREFIX/usr/bin/$TARGET-clang CXX=$PREFIX/usr/bin/$TARGET-clang++ AR=$PREFIX/usr/bin/llvm-ar-gnu RANLIB=$PREFIX/usr/bin/llvm-ranlib-gnu

cd ..
mkdir build-mingw-x86_64-llvm-git
cd build-mingw-x86_64-llvm-git

cmake -G"Ninja" \
    -DCMAKE_C_COMPILER=$CC \
    -DCMAKE_CXX_COMPILER=$CXX \
    -DCMAKE_C_FLAGS="-D__CRT__NO_INLINE" \
    -DCMAKE_CXX_FLAGS="-D__CRT__NO_INLINE" \
    -DCMAKE_CROSSCOMPILING=TRUE \
    -DCMAKE_SYSTEM_NAME=Windows \
    -DCMAKE_BASE_NAME=GNU \
    -DCMAKE_AR=$PREFIX/usr/bin/llvm-ar-gnu \
    -DCMAKE_RANLIB=$PREFIX/usr/bin/llvm-ranlib-gnu \
    -DCMAKE_INSTALL_PREFIX="/usr" \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_TABLEGEN=$PREFIX/usr/bin/llvm-tblgen \
    -DCLANG_TABLEGEN=$PREFIX/usr/bin/clang-tblgen \
    -DLLVM_DEFAULT_TARGET_TRIPLE="x86_64--windows-gnu" \
    -DLLVM_TARGET_ARCH=X86 \
    -DLLVM_TARGETS_TO_BUILD=X86 \
    -DLLVM_ENABLE_ASSERTIONS=OFF \
    -DLLVM_ENABLE_THREADS=0 \
    -DPYTHON_EXECUTABLE=/usr/bin/python \
    -DLLVM_ENABLE_FFI=OFF \
    -DLLVM_ENABLE_SPHINX=OFF \
    -DCMAKE_VERBOSE_MAKEFILE=ON \
    -DLLVM_BUILD_TESTS=OFF \
    -DLLVM_BUILD_STATIC=TRUE \
    -DCLANG_ENABLE_ARCMT=OFF \
    -DLLVM_INCLUDE_TESTS=OFF \
    -DCLANG_INCLUDE_TESTS=OFF \
    -DLIBCLANG_BUILD_STATIC=ON \
    -DBUILD_SHARED_LIBS=OFF \
    ../llvm

#-DCMAKE_C_FLAGS="-D__CRT__NO_INLINE" \
#-DCMAKE_CXX_FLAGS="-D_GNU_SOURCE -D_LIBCPP_HAS_NO_CONSTEXPR -D__CRT__NO_INLINE" \
    

# -DCLANG_TABLEGEN=$PREFIX/usr/bin/clang-tblgen \  
 # -DLLVM_ON_WIN32=TRUE \

ninja
DESTDIR=/Users/martell/llvm/mingw-w64-x86_64 ninja install
